
// This file has been generated by the GUI designer. Do not modify.
namespace F_D
{
	public partial class LecturerWindow
	{
		private global::Gtk.Fixed fixed1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget F_D.LecturerWindow
			this.Name = "F_D.LecturerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("LecturerWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child F_D.LecturerWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 523;
			this.Show();
		}
	}
}
