
// This file has been generated by the GUI designer. Do not modify.
namespace F_D
{
	public partial class SignupWindow
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.RadioButton radiobutton1;

		private global::Gtk.RadioButton radiobutton2;

		private global::Gtk.RadioButton radiobutton3;

		private global::Gtk.Label label5;

		private global::Gtk.Entry entry1;

		private global::Gtk.Entry entry2;

		private global::Gtk.Entry entry3;

		private global::Gtk.Label label6;

		private global::Gtk.Entry entry4;

		private global::Gtk.Label label7;

		private global::Gtk.Entry entry5;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.Entry entry7;

		private global::Gtk.Label label10;

		private global::Gtk.Entry entry8;

		private global::Gtk.Label label11;

		private global::Gtk.Entry entry9;

		private global::Gtk.Button button1;

		private global::Gtk.Button button2;

		private global::Gtk.Label label4;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.Label label15;

		private global::Gtk.Label label14;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.Label label16;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget F_D.SignupWindow
			this.Name = "F_D.SignupWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("SignupWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child F_D.SignupWindow.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.fixed3.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label1]));
			w1.X = 330;
			w1.Y = 18;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("label2");
			this.fixed3.Add(this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label2]));
			w2.X = 90;
			w2.Y = 88;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("label3");
			this.fixed3.Add(this.label3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label3]));
			w3.X = 120;
			w3.Y = 140;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.radiobutton1 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("radiobutton1"));
			this.radiobutton1.CanFocus = true;
			this.radiobutton1.Name = "radiobutton1";
			this.radiobutton1.DrawIndicator = true;
			this.radiobutton1.UseUnderline = true;
			this.radiobutton1.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.fixed3.Add(this.radiobutton1);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.radiobutton1]));
			w4.X = 260;
			w4.Y = 83;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.radiobutton2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("radiobutton2"));
			this.radiobutton2.CanFocus = true;
			this.radiobutton2.Name = "radiobutton2";
			this.radiobutton2.DrawIndicator = true;
			this.radiobutton2.UseUnderline = true;
			this.radiobutton2.Group = this.radiobutton1.Group;
			this.fixed3.Add(this.radiobutton2);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.radiobutton2]));
			w5.X = 380;
			w5.Y = 83;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.radiobutton3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("radiobutton3"));
			this.radiobutton3.CanFocus = true;
			this.radiobutton3.Name = "radiobutton3";
			this.radiobutton3.DrawIndicator = true;
			this.radiobutton3.UseUnderline = true;
			this.radiobutton3.Group = this.radiobutton1.Group;
			this.fixed3.Add(this.radiobutton3);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.radiobutton3]));
			w6.X = 520;
			w6.Y = 83;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.fixed3.Add(this.label5);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label5]));
			w7.X = 120;
			w7.Y = 220;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.fixed3.Add(this.entry1);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry1]));
			w8.X = 300;
			w8.Y = 136;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '●';
			this.fixed3.Add(this.entry2);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry2]));
			w9.X = 300;
			w9.Y = 176;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.fixed3.Add(this.entry3);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry3]));
			w10.X = 300;
			w10.Y = 216;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("label6");
			this.fixed3.Add(this.label6);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label6]));
			w11.X = 70;
			w11.Y = 310;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.entry4 = new global::Gtk.Entry();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '●';
			this.fixed3.Add(this.entry4);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry4]));
			w12.X = 170;
			w12.Y = 306;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("label7");
			this.fixed3.Add(this.label7);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label7]));
			w13.X = 420;
			w13.Y = 310;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.entry5 = new global::Gtk.Entry();
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.IsEditable = true;
			this.entry5.InvisibleChar = '●';
			this.fixed3.Add(this.entry5);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry5]));
			w14.X = 520;
			w14.Y = 306;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("label8");
			this.fixed3.Add(this.label8);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label8]));
			w15.X = 70;
			w15.Y = 350;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("label9");
			this.fixed3.Add(this.label9);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label9]));
			w16.X = 420;
			w16.Y = 350;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.entry7 = new global::Gtk.Entry();
			this.entry7.CanFocus = true;
			this.entry7.Name = "entry7";
			this.entry7.IsEditable = true;
			this.entry7.InvisibleChar = '●';
			this.fixed3.Add(this.entry7);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry7]));
			w17.X = 520;
			w17.Y = 346;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.fixed3.Add(this.label10);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label10]));
			w18.X = 70;
			w18.Y = 390;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.entry8 = new global::Gtk.Entry();
			this.entry8.CanFocus = true;
			this.entry8.Name = "entry8";
			this.entry8.IsEditable = true;
			this.entry8.InvisibleChar = '●';
			this.fixed3.Add(this.entry8);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry8]));
			w19.X = 170;
			w19.Y = 386;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("label2");
			this.fixed3.Add(this.label11);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label11]));
			w20.X = 420;
			w20.Y = 390;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.entry9 = new global::Gtk.Entry();
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '●';
			this.fixed3.Add(this.entry9);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry9]));
			w21.X = 520;
			w21.Y = 386;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.fixed3.Add(this.button1);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button1]));
			w22.X = 209;
			w22.Y = 460;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.fixed3.Add(this.button2);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button2]));
			w23.X = 545;
			w23.Y = 464;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.fixed3.Add(this.label4);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label4]));
			w24.X = 120;
			w24.Y = 180;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.fixed3.Add(this.hseparator1);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.hseparator1]));
			w25.X = 275;
			w25.Y = 275;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.fixed3.Add(this.hseparator2);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.hseparator2]));
			w26.X = 201;
			w26.Y = 261;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.fixed3.Add(this.hseparator3);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.hseparator3]));
			w27.X = 358;
			w27.Y = 260;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.Name = "vseparator1";
			this.fixed3.Add(this.vseparator1);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.vseparator1]));
			w28.X = 655;
			w28.Y = 172;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("label3");
			this.fixed3.Add(this.label12);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label12]));
			w29.X = 530;
			w29.Y = 140;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.fixed3.Add(this.label13);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label13]));
			w30.X = 530;
			w30.Y = 180;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("label6");
			this.fixed3.Add(this.label15);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label15]));
			w31.X = 520;
			w31.Y = 420;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.fixed3.Add(this.label14);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label14]));
			w32.X = 170;
			w32.Y = 420;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Male"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Female"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Secret"));
			this.combobox1.Name = "combobox1";
			this.combobox1.Active = 0;
			this.fixed3.Add(this.combobox1);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.combobox1]));
			w33.X = 170;
			w33.Y = 346;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.fixed3.Add(this.label16);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label16]));
			w34.X = 720;
			w34.Y = 350;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 906;
			this.DefaultHeight = 515;
			this.Show();
			this.button1.Clicked += new global::System.EventHandler(this.Goback_btn);
			this.button2.Clicked += new global::System.EventHandler(this.CreateAccount);
		}
	}
}
